Repository US-EPA-CAMD/easey-ecmps-ui, pull requests merged in 2021-12, with the labels that each got.

#200 Google analytics updated
  package.json
  src/config.js
  src/index.js
  yarn.lock
Labels: Emissioners, Tech Team

#201 Changed to structure of google tag code
  src/components/App/App.js
  src/config.js
  src/index.js
Labels: Emissioners, Tech Team

#202 Changes to import
  src/components/App/App.js
Labels: Emissioners, Tech Team

#203 Updated tag manager
  src/components/App/App.js
Labels: Emissioners, Tech Team

#204 accepting 201 status code for successful responses
  src/utils/api/apiUtils.js
Labels: Emissioners

#205 footer issue fixed
  src/components/Layout/Layout.js
Labels: bug

#207 Feature/630 view locations relationships
  src/additional-functions/create-modal-input-controls.js
  src/additional-functions/dataTable-props.js
  src/additional-functions/retrieve-dropdown-api.js
  src/components/CustomAccordion/CustomAccordion.js
  src/components/HeaderInfo/HeaderInfo.js
  src/components/LeftNavigation/LeftNavigation.js
  src/components/ModalAddComponent/ModalAddComponent.js
  src/components/MonitoringPlanTabRender/MonitoringPlanTabRender.js
  src/components/datatablesContainer/DataTableAnalyzerRanges/DataTableAnalyzerRanges.js
  src/components/datatablesContainer/DataTableAssert/DataTableAssert.js
  src/components/datatablesContainer/DataTableDefaults/DataTableDefaults.js
  src/components/datatablesContainer/DataTableLEEQualifications/DataTableLEEQualifications.js
  src/components/datatablesContainer/DataTableLMEQualifications/DataTableLMEQualifications.js
  src/components/datatablesContainer/DataTableMethod/DataTableMethod.js
  src/components/datatablesContainer/DataTablePCTQualifications/DataTablePCTQualifications.js
  src/components/datatablesContainer/DataTableSystems/DataTableSystems.js
  src/components/datatablesContainer/DataTableSystemsComponents/DataTableSystemsComponents.js
  src/utils/api/dataManagementApi.js
  src/utils/api/monitoringPlansApi.js
  src/utils/selectors/assert.js
  src/utils/selectors/monitoringPlanLocationAttributes.js
Labels: Emissioners

#208 Feature/630 view locations relationships
  src/utils/selectors/monitoringPlanLocationAttributes.js
Labels: Emissioners

#210 Feature/1703 edit attributes
  src/additional-functions/extract-user-input.js
  src/components/ComingSoon/ComingSoon.test.js
  src/components/ModalDetails/ModalDetails.js
  src/components/ModalDetails/ModalDetails.test.js
  src/components/MonitoringPlanTabRender/MonitoringPlanTabRender.js
  src/components/NotFound/NotFound.js
  src/components/NotFound/NotFound.test.js
  src/components/datatablesContainer/DataTableAssert/DataTableAssert.js
  src/components/datatablesContainer/DataTableDefaults/DataTableDefaults.js
  src/components/datatablesContainer/DataTableDefaults/DataTableDefaults.test.js
  src/components/datatablesContainer/DataTableFormulas/DataTableFormulas.js
  src/components/datatablesContainer/DataTableFormulas/DataTableFormulas.test.js
  src/components/datatablesContainer/DataTableFuelData/DataTableFuelData.js
  src/components/datatablesContainer/DataTableFuelData/DataTableFuelData.test.js
  src/components/datatablesContainer/DataTableLoads/DataTableLoads.js
  src/components/datatablesContainer/DataTableLoads/DataTableLoads.test.js
  src/components/datatablesContainer/DataTableSpans/DataTableSpans.js
  src/components/datatablesContainer/DataTableSpans/DataTableSpans.test.js
  src/components/datatablesContainer/DataTableUnitControl/DataTableUnitControl.js
  src/components/datatablesContainer/DataTableUnitControl/DataTableUnitControl.test.js
Labels: Emissioners

#211 Feature/2332 read evaluation status
  src/components/HeaderInfo/HeaderInfo.js
  src/components/HeaderInfo/HeaderInfo.scss
  src/config.js
Labels: Emissioners

#209 GTM-Containers
  src/components/App/App.js
  src/config.js
  src/index.js
Labels: Emissioners, Tech Team

#213 Feature/2332 trigger quartz job for eval
  src/components/HeaderInfo/HeaderInfo.js
  src/utils/api/quartzApi.js
Labels: Emissioners

#214 Feature/1702 create attributes
  src/additional-functions/add-active-class.js
  src/additional-functions/add-active-class.test.js
  src/additional-functions/create-modal-input-controls.js
  src/additional-functions/extract-user-input.js
  src/additional-functions/retrieve-dropdown-api.js
  src/components/DataTableRender/DataTableRender.js
  src/components/HeaderInfo/HeaderInfo.test.js
  src/components/ModalDetails/ModalDetails.js
  src/components/MonitoringPlanTabRender/MonitoringPlanTabRender.js
  src/components/datatablesContainer/DataTableAnalyzerRanges/DataTableAnalyzerRanges.test.js
  src/components/datatablesContainer/DataTableAssert/DataTableAssert.js
  src/components/datatablesContainer/DataTableAssert/DataTableAssert.test.js
  src/components/datatablesContainer/DataTableMats/DataTableMats.js
  src/components/datatablesContainer/DataTableMethod/DataTableMethod.js
  src/components/datatablesContainer/DataTablePCTQualifications/DataTablePCTQualifications.js
  src/components/datatablesContainer/DataTableRectangularDucts/DataTableRectangularDucts.js
  src/components/datatablesContainer/DataTableRectangularDucts/DataTableRectangularDucts.test.js
  src/components/datatablesContainer/DataTableSystems/DataTableSystems.js
  src/utils/api/monitoringPlansApi.js
  src/utils/selectors/assert.js
  src/utils/selectors/assert.test.js
  src/utils/selectors/facilities.js
  src/utils/selectors/facilities.test.js
  src/utils/selectors/monitoringPlanFormulas.js
  src/utils/selectors/monitoringPlanFormulas.test.js
  src/utils/selectors/monitoringPlanLEEQualifications.js
  src/utils/selectors/monitoringPlanLEEQualifications.test.js
  src/utils/selectors/monitoringPlanLMEQualifications.js
  src/utils/selectors/monitoringPlanLMEQualifications.test.js
  src/utils/selectors/monitoringPlanLocationAttributes.js
  src/utils/selectors/monitoringPlanLocationAttributes.test.js
  src/utils/selectors/monitoringPlanRectangularDucts.test.js
  src/utils/selectors/monitoringPlanSpans.js
  src/utils/selectors/monitoringPlanSpans.test.js
  src/utils/selectors/monitoringPlanSystems.js
  src/utils/selectors/monitoringPlanSystems.test.js
  src/utils/selectors/monitoringPlanUnitCapacity.js
  src/utils/selectors/monitoringPlanUnitCapacity.test.js
  src/utils/selectors/monitoringPlanUnitControls.js
  src/utils/selectors/monitoringPlanUnitControls.test.js
Labels: Emissioners

#215 Feature/unit testing
  src/components/datatablesContainer/DataTableConfigurations/DataTableConfigurations.test.js
  src/components/datatablesContainer/DataTableSystemsComponents/DataTableSystemsComponents.test.js
  src/components/datatablesContainer/SelectFacilitiesDataTable/SelectFacilitiesDataTable.js
  src/components/datatablesContainer/SelectFacilitiesDataTable/SelectFacilitiesDataTable.test.js
Labels: Emissioners

#216 Feature/unit testing
  src/additional-functions/retrieve-dropdown-api.js
  src/components/datatablesContainer/DataTableLEEQualifications/DataTableLEEQualifications.js
  src/components/datatablesContainer/DataTableLEEQualifications/DataTableLEEQualifications.test.js
  src/components/datatablesContainer/DataTableLMEQualifications/DataTableLMEQualifications.js
  src/components/datatablesContainer/DataTableLMEQualifications/DataTableLMEQualifications.test.js
  src/components/datatablesContainer/DataTablePCTQualifications/DataTablePCTQualifications.js
  src/components/datatablesContainer/DataTablePCTQualifications/DataTablePCTQualifications.test.js
  src/components/datatablesContainer/SelectFacilitiesDataTable/SelectFacilitiesDataTable.js
Labels: Emissioners

#217 Feature/2347 2348 homepage and reporting instructions content
  src/components/AboutHome/AboutHome.js
  src/components/ReportingInstructions/ReportingInstructions.js
  src/components/ReportingInstructions/monitoring-plan-json-format.json
Labels: Emissioners

#218 Feature/fixing homepage and reporting instructions urls
  src/components/AboutHome/AboutHome.js
  src/components/ReportingInstructions/ReportingInstructions.js
Labels: Emissioners

#219 Feature/unit testing
  src/additional-functions/dataTable-props.js
  src/utils/selectors/monitoringPlanLocationAttributes.js
  src/utils/selectors/monitoringPlanLocationAttributes.test.js
Labels: Emissioners

#220 Fixing homepage for beta 2.0
  src/components/AboutHome/AboutHome.js
Labels: Emissioners

#221 Feature/unit testing
  src/components/MonitoringPlanTabRender/MonitoringPlanTabRender.js
  src/components/datatablesContainer/DataTableAssert/DataTableAssert.js
  src/utils/api/monitoringPlansApi.js
Labels: Emissioners

#225 Eval status refresh fixes
  src/components/HeaderInfo/HeaderInfo.js
  src/config.js
Labels: Emissioners

#224 Feature/unit testing
  src/components/HeaderInfo/HeaderInfo.js
  src/components/HeaderInfo/HeaderInfo.test.js
  src/components/MonitoringPlanEvaluationReport/MonitoringPlanEvaluationReport.js
  src/components/MonitoringPlanEvaluationReport/MonitoringPlanEvaluationReport.test.js
  src/components/SubHeader/SubHeader.js
  src/components/SubHeader/SubHeader.test.js
  src/components/datatablesContainer/DataTableAnalyzerRanges/DataTableAnalyzerRanges.test.js
  src/utils/api/monitoringPlansApi.js
  src/utils/selectors/monitoringPlanLocationAttributes.test.js
Labels: Emissioners

#226 Feature/unit testing
  src/utils/api/monitoringPlansApi.js
Labels: Emissioners

#227 508 fixes for header / right side nav
  package.json
  yarn.lock
Labels: bug

#228 Fixing refresh loop and compilation warnings
  src/components/AboutHome/AboutHome.js
  src/components/HeaderInfo/HeaderInfo.js
  src/components/MonitoringPlanEvaluationReport/MonitoringPlanEvaluationReport.js
  src/components/Resources/Resources.js
Labels: Emissioners

#229 warning removed from console
  src/components/AboutHome/AboutHome.js
  src/components/MonitoringPlanEvaluationReport/MonitoringPlanEvaluationReport.js
  src/components/Resources/Resources.js
Labels: bug

#230 Feature/2363 home screen
  src/components/AboutHome/AboutHome.js
  src/components/AboutHome/AboutHome.scss
  src/components/DataTableRender/DataTableRender.js
Labels: Emissioners

#231 configured cdx/cbs links for login and user profile menu
  manifest-vars.test.yml
  manifest-vars.yml
  manifest.yml
  src/components/Login/Login.js
  src/components/SubHeader/SubHeader.js
  src/config.js
Labels: Emissioners

#232 Feature/2363 home screen
  src/components/AboutHome/AboutHome.js
  src/components/AboutHome/AboutHome.scss
Labels: Emissioners

#233 Configuring login and profile menu links
  manifest-vars.yml
  manifest.yml
Labels: Emissioners

#234 Feature/2363 home screen
  src/components/AboutHome/AboutHome.js
Labels: Emissioners

#235 Adding base urls to other envs and renaming user id var
  manifest-vars.beta.yml
  manifest-vars.prod.yml
  manifest-vars.staging.yml
  manifest-vars.test.yml
  manifest-vars.yml
  manifest.yml
  src/components/Login/Login.js
  src/config.js
Labels: Emissioners

#236 adding timeout for refresh eval status loop
  manifest-vars.beta.yml
  manifest-vars.prod.yml
  manifest-vars.staging.yml
  manifest-vars.test.yml
  manifest-vars.yml
  manifest.yml
  src/components/HeaderInfo/HeaderInfo.js
  src/config.js
Labels: Emissioners

#238 fixed issue with switched links for create account and forgot passwor…
  src/config.js
Labels: Emissioners

#240 Feat/global fonts
  package.json
  public/index.html
  src/additional-scss/_global-styles.scss
  src/additional-scss/_react-datatable-component-override.scss
  src/additional-scss/_variables.scss
  src/components/AboutHome/AboutHome.js
  src/components/AboutHome/AboutHome.scss
  src/components/DataTableRender/DataTableRender.scss
Labels: Emissioners

#243 removing unused state in header component to clean up build warning
  src/components/HeaderInfo/HeaderInfo.js
Labels: Emissioners

#244 reverting styling
  public/index.html
Labels: Emissioners

#246 Fixing UI to refresh eval status after update or create
  .gitignore
  src/components/HeaderInfo/HeaderInfo.js
Labels: Emissioners

#248 fixed swagger url to use mon plan api url from env var and created en…
  manifest-vars.yml
  manifest.yml
  src/components/ReportingInstructions/ReportingInstructions.js
  src/config.js
Labels: Emissioners

#250 Feat/global fonts
  src/additional-scss/_global-styles.scss
Labels: Emissioners

#251 Fixing inconsistencies with user checkout and audit
  src/components/HeaderInfo/HeaderInfo.js
Labels: Emissioners

#252 Bug/2418 fix styling for info msg
  src/components/HeaderInfo/HeaderInfo.js
Labels: Emissioners

#253 Bug/2419 fixing issues with editing sections
  src/additional-functions/dataTable-props.js
  src/components/MonitoringPlanTabRender/MonitoringPlanTabRender.js
  src/components/Tabs/Tabs.js
  src/components/datatablesContainer/DataTableMats/DataTableMats.js
  src/components/datatablesContainer/DataTableSystems/DataTableSystems.js
  src/utils/api/monitoringPlansApi.js
  src/utils/selectors/assert.js
Labels: Emissioners

#256 changing radio names to correct data type
  src/components/datatablesContainer/DataTableSystems/DataTableSystems.js
Labels: Emissioners

#255 fixing audit message for global view - wrong reference for userid
  src/components/HeaderInfo/HeaderInfo.js
Labels: Emissioners

#258 Feature/2360 mp eval report new screen
  src/components/App/App.js
  src/components/EvaluationReport/EvaluationReport.js
  src/components/EvaluationReport/EvaluationReport.scss
  src/components/EvaluationReport/EvaluationReport.test.js
  src/components/Layout/Layout.js
  src/components/MonitoringPlanEvaluationReport/MonitoringPlanEvaluationReport.js
  src/components/MonitoringPlanEvaluationReport/MonitoringPlanEvaluationReport.scss
  src/utils/api/facilityApi.js
  src/utils/api/monitoringPlansApi.js
Labels: Emissioners

#259 fixing beta contact form links and dev cdx link
  src/components/AboutHome/AboutHome.js
  src/config.js
Labels: Emissioners

#260 Feat/report portal
  package.json
  src/additional-scss/_settings.scss
  src/components/App/App.js
  src/components/App/App.scss
  src/components/EvaluationReport/EvaluationReport.js
  src/components/EvaluationReport/EvaluationReport.scss
  src/components/HeaderInfo/HeaderInfo.js
  src/components/Login/Login.js
  src/components/MonitoringPlanEvaluationReport/MonitoringPlanEvaluationReport.js
  src/components/ReportGenerator/ReportGenerator.js
  src/components/ReportGenerator/ReportGenerator.scss
  src/components/ReportGenerator/ReportGenerator.test.js
  yarn.lock
Labels: Emissioners

#261 Feat/report portal
  src/animations/transitions.scss
  src/components/App/App.js
  src/components/HeaderInfo/HeaderInfo.js
  src/components/Login/Login.js
  src/components/MonitoringPlanEvaluationReport/MonitoringPlanEvaluationReport.js
  src/components/ReportGenerator/ReportGenerator.js
  src/components/ReportGenerator/ReportGenerator.scss
  src/components/WideHeader/title.png
Labels: Emissioners

#262 location of button fixed
  src/components/SubHeader/SubHeader.js
Labels: bug

#263 Feat/help support text 2436
  package.json
  src/components/HelpSupport/HelpSupport.js
  yarn.lock
Labels: Emissioners

#264 Bug/2417 refactoring mdm calls
  .vscode/launch.json
  src/additional-functions/data-table-section-and-store-names.js
  src/additional-functions/retrieve-dropdown-api.js
  src/components/DataTableRender/DataTableRender.js
  src/components/HeaderInfo/HeaderInfo.js
  src/components/datatablesContainer/DataTableAnalyzerRanges/DataTableAnalyzerRanges.js
  src/components/datatablesContainer/DataTableAssert/DataTableAssert.js
  src/components/datatablesContainer/DataTableLEEQualifications/DataTableLEEQualifications.js
  src/components/datatablesContainer/DataTableLMEQualifications/DataTableLMEQualifications.js
  src/components/datatablesContainer/DataTableMats/DataTableMats.js
  src/components/datatablesContainer/DataTableMethod/DataTableMethod.js
  src/components/datatablesContainer/DataTablePCTQualifications/DataTablePCTQualifications.js
  src/components/datatablesContainer/DataTableQualifications/DataTableQualifications.js
  src/components/datatablesContainer/DataTableSystems/DataTableSystems.js
  src/components/datatablesContainer/DataTableSystemsComponents/DataTableSystemsComponents.js
  src/store/actions/actionTypes.js
  src/store/actions/apiStatusActions.js
  src/store/actions/dropdowns.js
  src/store/reducers/dropdowns.js
  src/store/reducers/index.js
  src/store/reducers/initialState.js
Labels: Emissioners

#267 Bug/2417 refactoring mdm calls
  src/components/SubHeader/SubHeader.test.js
  src/components/datatablesContainer/DataTableAssert/DataTableAssert.test.js
  src/components/datatablesContainer/DataTableMats/DataTableMats.test.js
  src/components/datatablesContainer/DataTableMethod/DataTableMethod.test.js
  src/components/datatablesContainer/DataTableSystems/DataTableSystems.test.js
  src/components/datatablesContainer/DataTableSystemsComponents/DataTableSystemsComponents.test.js
Labels: Emissioners

#266 removing failing tests
  src/components/datatablesContainer/DataTableAnalyzerRanges/DataTableAnalyzerRanges.test.js
  src/components/datatablesContainer/DataTableLEEQualifications/DataTableLEEQualifications.test.js
  src/components/datatablesContainer/DataTableLMEQualifications/DataTableLMEQualifications.test.js
  src/components/datatablesContainer/DataTablePCTQualifications/DataTablePCTQualifications.test.js
  src/components/datatablesContainer/DataTableQualifications/DataTableQualifications.test.js
  src/store/actions/monitoringPlans.test.js
Labels: Emissioners

#270 Feature/styling issues 2401
  public/index.html
  src/additional-functions/app-error.js
  src/additional-scss/_global-styles.scss
  src/additional-scss/_uswds-global-overrides.scss
  src/additional-scss/_variables.scss
  src/components/HeaderInfo/HeaderInfo.js
  src/components/Layout/Layout.js
  src/components/Modal/Modal.js
  src/components/Modal/Modal.scss
  src/components/ReportGenerator/ReportGenerator.scss
  src/components/SubHeader/SubHeader.js
  src/components/Tabs/Tabs.js
  src/components/Tabs/Tabs.scss
  src/utils/api/apiUtils.js
  src/utils/api/easeyAuthApi.js
Labels: Emissioners

#271 fixing bugs with mdm dropdowns for data tables using DataTableAssert …
  src/additional-functions/data-table-section-and-store-names.js
  src/components/HeaderInfo/HeaderInfo.js
  src/components/datatablesContainer/DataTableAssert/DataTableAssert.js
  src/store/reducers/dropdowns.js
  src/store/reducers/initialState.js
Labels: Emissioners

#273 Fixing incorrect parsing of location ids
  .gitignore
  src/components/MonitoringPlanTabRender/MonitoringPlanTabRender.js
Labels: Emissioners

#274 styling changes complete
  src/additional-scss/_uswds-global-overrides.scss
  src/components/HeaderInfo/HeaderInfo.js
  src/components/ModalDetails/ModalDetails.js
  src/components/SubHeader/SubHeader.js
  src/components/Tabs/Tabs.js
  src/components/Tabs/Tabs.scss
Labels: Emissioners
