Repository US-EPA-CAMD/easey-ecmps-ui, pull requests merged in 2023-06, with the labels that each got.

#1110 fix/FAQ
  src/components/FAQ/FAQ.js
  src/utils/constants/menuTopics.js
Labels: Tech Team

#1111 Fix/Error-Suppression
  src/utils/constants/menuTopics.js
Labels: Tech Team

#1112 Automated tests yml
  .github/workflows/automated-tests.yml
Labels: Test Automation

#1115 Automated tests yml
  .github/workflows/automated-tests.yml
Labels: Test Automation

#1117 Feature/5288 em submission
  package.json
  src/additional-functions/app-error.js
  src/components/App/App.js
  src/components/EvaluateAndSubmit/EvaluateAndSubmit.js
  src/components/EvaluateAndSubmit/FilterForm/FilterForm.js
  src/components/SystemAdmin/SubmissionAccess/FilterFormAdmin/FilterFormAdmin.js
  src/components/SystemAdmin/SubmissionAccess/FilterFormAdmin/FilterFormAdmin.test.js
  src/components/SystemAdmin/SubmissionAccess/SubmissionAccess.js
  src/components/SystemAdmin/SubmissionAccess/SubmissionAccess.test.js
Labels: Emissioners

#1120 fix: update em-supp status dropdown position
  src/components/ErrorSuppression/ErrorSuppressionFilters/ErrorSuppressionFilters.js
Labels: Emissioners

#1118 fix/4913 - Error Suppression - Filter Facilities Dropdown
  src/components/ErrorSuppression/ErrorSuppressionFilters/ErrorSuppressionFilters.js
Labels: Emissioners

#1122 🐛 Bug/5249: Emission UI Historical Import Reporting Period Dropdown
  src/components/QAImportHistoricalDataPreview/QAImportHistoricalDataPreview.js
  src/components/ReportingPeriodSelector/ReportingPeriodSelector.js
  src/components/export/ExportTab/ExportTab.js
Labels: Emissioners

#1123 Feature/5289 qa cert data UI
  src/additional-functions/system-admin-section-and-store-names.js
  src/components/App/App.js
  src/components/DropdownSelection/DropdownSelection.js
  src/components/QACertTestSummaryHeaderInfo/QACertTestSummaryHeaderInfo.js
  src/components/SystemAdmin/SubmissionAccess/FilterFormAdmin/FilterFormAdmin.js
  src/components/SystemAdmin/SubmissionAccess/SubmissionAccess.js
Labels: Emissioners

#1125 fix/5212 - Keep Selected Report Periods on Emissions Checkout/In
  src/components/HeaderInfo/HeaderInfo.js
Labels: Emissioners

#1126 Feature/5289 qa cert data UI
  src/components/SystemAdmin/SubmissionAccess/FilterFormAdmin/FilterFormAdmin.js
Labels: Emissioners

#1128 Feature/5289 qa cert data UI
  src/components/QADataTableRender/QADataTableRender.js
  src/components/SystemAdmin/SubmissionAccess/FilterFormAdmin/FilterFormAdmin.js
  src/components/datatablesContainer/DataTableAssert/DataTableAssert.js
  src/components/qaDatatablesContainer/QAExpandableRowsRender/QAExpandableRowsRender.js
Labels: Emissioners Emissions

#1133 🐛Bug/5331: Error Suppression UI Clone Record
  src/components/ErrorSuppression/AddErrorSuppressionModal/AddErrorSuppressionModal.js
  src/components/ErrorSuppression/ErrorSuppressionDataContainer/ErrorSuppressionDataContainer.js
Labels: Emissioners

#1135 ✨ Feature: Create Open/Extend/Approve/Close Submission Pop Out
  src/components/AdminMaintenance/EmSubmissionData/EmSubmissionData.js
  src/components/AdminMaintenance/EmSubmissionPopOut/EmSubmissionPopout.js
  src/components/Modal/Modal.js
Labels: Emissioners

#1145 fix/Evaluate-Refresh
  src/components/App/App.js
  src/components/EvaluateAndSubmit/ReviewCell/ReviewCell.js
Labels: Tech Team

#1146 ✨Feature/5231: Implement Open Submission Record API Call
  src/components/AdminMaintenance/AdminMaintenance.js
  src/components/AdminMaintenance/EmSubmissionData/EmSubmissionData.js
  src/components/AdminMaintenance/EmSubmissionPopOut/EmSubmissionPopout.js
  src/components/AdminMaintenance/FilterFormAdmin/FilterFormAdmin.js
  src/components/ReportingPeriodSelector/ReportingPeriodSelector.js
  src/components/export/ExportTab/ExportTab.test.mocks.js
  src/utils/api/adminManagementApi.js
  src/utils/api/qaCertificationsAPI.js
Labels: Emissioners

#1147 feature/5226-select-box-functionality
  src/components/AdminMaintenance/EmSubmissionData/EmSubmissionData.js
Labels: Emissioners

#1151 Feature/5221 create view em submission popout layout fix merge conflicts
  src/components/AdminMaintenance/EmSubmissionData/EmSubmissionData.js
Labels: Emissioners

#1152 Feature/5232 implement extend submission access record api call
  src/components/AdminMaintenance/EmSubmissionData/EmSubmissionData.js
  src/components/AdminMaintenance/EmSubmissionPopOut/EmSubmissionPopout.js
  src/utils/api/adminManagementApi.js
Labels: Emissioners

#1155 fix/Eval
  src/components/EvaluateAndSubmit/ReviewCell/ReviewCell.js
  src/components/EvaluateAndSubmit/TableRender/TableRender.js
Labels: Tech Team

#1156 fix/Inactivity
  src/components/InactivityTracker/InactivityTracker.js
Labels: Tech Team
