Repository US-EPA-CAMD/easey-ecmps-ui, pull requests merged in 2023-08, with the labels that each got.

#1205 Unit-test/5371: ECMPS Test Files Group 26
  src/components/ReportGenerator/Report/Report.test.js
  src/components/ReportGenerator/ReportGenerator.test.js
  src/components/ReportingInstructions/ReportingInstructions.test.js
Labels: Emissioners

#1201 Feature/5365 unit test group 21
  src/components/MonitoringPlanHome/MonitoringPlanHome.test.js
  src/components/MonitoringPlanTabRender/MonitoringPlanTabRender.js
  src/components/MonitoringPlanTabRender/MonitoringPlanTabRender.test.js
  src/components/MultiSelectCombobox/MultiSelectCombobox.test.js
  src/utils/constants/moduleTitles.js
Labels: Emissioners

#1208 Feature/5368 test group 23
  src/components/QACertEventTabRender/QACertEventTabRender.test.js
  src/components/QACertTestSummaryHeaderInfo/QACertTestSummaryHeaderInfo.test.js
  src/components/QACertTestSummaryTab/QACertTestSummaryTab.test.js
Labels: Emissioners

#1211 Bug/5534 cycle time injection date
  src/additional-functions/extract-user-input.js
  src/additional-functions/extract-user-input.test.js
  src/components/qaDatatablesContainer/QAExpandableRowsRender/QAExpandableRowsRender.js
Labels: Emissioners

#1213 Unit-Tests/5376: ECMPS Test Files Group 31
  src/utils/api/apiUtils.test.js
Labels: Emissioners

#1215 fix/Wire-Submission
  src/components/EvaluateAndSubmit/EvaluateAndSubmit.js
  src/utils/api/camdServices.js
Labels: Tech Team

#1216 Unit-test/5377: ECMPS Test Files Group 32
  src/utils/api/easeyAuthApi.test.js
  src/utils/api/emissionsApi.test.js
  src/utils/api/facilityApi.test.js
Labels: Emissioners

#1212 fix/5533 - Save Unit Control Radio Values as Strings
  src/utils/api/monitoringPlansApi.js
Labels: Emissioners

#1217 Feature/5456 bug qa record
  src/additional-functions/qa-dataTable-props.js
  src/components/qaDatatablesContainer/QAExpandableRowsRender/QAExpandableRowsRender.js
  src/components/qaDatatablesContainer/QATestSummaryDataTable/QATestSummaryDataTable.js
Labels: Emissioners

#1218 fix secureAxios mock
  src/utils/api/monitoringPlansApi.test.js
Labels: Emissioners

#1220 fix/Left-Hand-Filter
  src/utils/constants/menuTopics.js
Labels: Tech Team

#1219 Unit-Tests/5379: ECMPS Test Files Group 34
  src/utils/selectors/assert.test.js
Labels: Emissioners

#1221 🐛 Bug/5550: EM Submission Extend Action
  src/components/AdminMaintenance/EmSubmissionData/EmSubmissionData.js
  src/components/AdminMaintenance/EmSubmissionData/EmSubmissionData.test.js
Labels: Emissioners

#1224 fix custom sort function
  src/components/QADataTableRender/QADataTableRender.js
  src/utils/selectors/QACert/TestSummary.js
Labels: Emissioners

#1226 fix/Quarter-Submission
  src/components/EvaluateAndSubmit/EvaluateAndSubmit.js
Labels: Tech Team

#1225 Unit-Tests/5380: ECMPS Test Files Group 35
  src/utils/selectors/monitoringPlanEvalData.test.js
Labels: Emissioners

#1228 Unit-Test/5382: ECMPS Test Files Group 37
  src/utils/selectors/monitoringPlanSystems.test.js
Labels: Emissioners

#1230 fix/Broken-Report
  src/components/App/App.js
Labels: Tech Team

#1229 Feature/5383 unit test 38
  src/utils/api/qaCertificationsAPI.js
  src/utils/selectors/QACert/assert.js
  src/utils/selectors/QACert/assert.test.js
Labels: Emissioners Emissions

#1227 add view modal
  src/components/ErrorSuppression/ErrorSuppressionDataContainer/ErrorSuppressionDataContainer.js
Labels: Emissioners

#1232 Feature/5563-screen-responsiveness-for-admin-pages
  src/components/AdminMaintenance/FilterFormAdmin/FilterFormAdmin.js
Labels: Emissioners

#1233 Bug/5514 mats bulk file test number dropdown
  src/components/ImportModal/ImportModalMatsContent/ImportModalMatsContent.js
  src/utils/api/qaCertificationsAPI.js
Labels: Emissioners

#1234 🐛 Bug/5585: UI Home Upper Menu
  src/components/SubHeader/SubHeader.js
  src/styles/_uswds-overrides.scss
Labels: Emissioners

#1238 feature/Mats-Submission
  src/components/EvaluateAndSubmit/ColumnMappings.js
  src/components/EvaluateAndSubmit/DataTables/DataTables.js
  src/components/EvaluateAndSubmit/EvaluateAndSubmit.js
  src/components/EvaluateAndSubmit/ReviewCell/ReviewCell.js
  src/components/EvaluateAndSubmit/TableRender/TableRender.js
  src/components/SubmissionSuccessModal/SubmissionSuccessModal.js
  src/components/SubmissionSuccessModal/SubmissionSuccessModal.test.js
  src/utils/api/qaCertificationsAPI.js
Labels: Tech Team

#1235 Feature/5513 mats bulk file import
  src/components/ImportModal/ImportModalMatsContent/ImportModalMatsContent.js
  src/components/QACertTestSummaryHeaderInfo/QACertTestSummaryHeaderInfo.js
  src/utils/api/camdServices.js
Labels: Emissioners

#1239 fix/Styling-Modal
  src/components/SubmissionSuccessModal/SubmissionSuccessModal.js
Labels: Tech Team

#1243 Bug/5607-qa-miscellaneous-expandable
  src/components/qaDatatablesContainer/QATestSummaryDataTable/QATestSummaryDataTable.js
Labels: Emissioners
