Repository US-EPA-CAMD/easey-ecmps-ui, pull requests merged in 2023-10, with the labels that each got.

#1285 🐛 Bug-508/5676-5677: EM Submission Access Checkbox and View Button Labels
  src/components/AdminMaintenance/EmSubmissionData/EmSubmissionData.js
Labels: bug, ECMPS Prod Team

#1286 🐛 Bug-508/5670-5671: QA Maintenance Checkbox and View Button Labels
  src/components/AdminMaintenance/QAMaintenance/QAMaintenanceData.js
Labels: bug, ECMPS Prod Team

#1284 Feature/5721-implement-error-logging
  package.json
  src/components/ErrorFallbackModal/ErrorFallbackModal.js
  src/index.js
  src/utils/api/apiUtils.js
  yarn.lock
Labels: ECMPS Prod Team

#1291 🐛 Bug-508/5681: EM Submission Access Pop Out Module Date Fields and Pickers
  src/components/AdminMaintenance/EmSubmissionPopOut/EmSubmissionPopout.js
Labels: bug, ECMPS Prod Team

#1289 Feature/5712 UI calendar cutoff
  src/components/Modal/Modal.js
  src/components/ModalDetails/ModalDetails.js
Labels: ECMPS Prod Team

#1295 fix/Mats
  src/components/ImportModal/ImportModalMatsContent/ImportModalMatsContent.js
  src/components/QACertTestSummaryHeaderInfo/QACertTestSummaryHeaderInfo.js
  src/utils/api/emissionsApi.js
  src/utils/api/monitoringPlansApi.js
  src/utils/api/qaCertificationsAPI.js
Labels: Tech Team

#1294 🐛 Bug/5736: QA Cert Event Dropdown
  src/components/qaDatatablesContainer/QACertEventTestExmpDataTable/QACertEventTestExmpDataTable.js
Labels: bug, ECMPS Prod Team

#1292 add position style to datatable
  src/components/datatablesContainer/DataTableQualifications/DataTableQualifications.js
  src/components/datatablesContainer/DataTableQualifications/DataTableQualifications.scss
Labels: Emissioners

#1299 fix/Submission-Status
  src/components/HeaderInfo/HeaderInfo.js
Labels: Tech Team

#1302 Feature/5615 modify protocol gas
  src/additional-functions/qa-dataTable-props.js
  src/components/Modal/Modal.js
  src/components/ModalDetails/ModalDetails.js
  src/components/ModalDetails/ModalDetails.scss
  src/components/MultiSelectCombobox/MultiSelectCombobox.js
  src/components/MultiSelectCombobox/MultiSelectCombobox.scss
  src/components/qaDatatablesContainer/QAExpandableRowsRender/QAExpandableRowsRender.js
  src/utils/api/dataManagementApi.js
  src/utils/api/dataManagementApi.test.js
  src/utils/selectors/QACert/assert.js
Labels: ECMPS Prod Team

#1304 fix/Report
  src/components/HeaderInfo/HeaderInfo.js
  src/utils/functions.js
Labels: Tech Team

#1307 fix: update admin maint column header
  src/components/AdminMaintenance/EmSubmissionData/EmSubmissionData.js
  src/components/AdminMaintenance/QAMaintenance/QAMaintenanceData.js
  src/components/AdminMaintenance/QAMaintenance/QAMaintenanceDataColumns.js
Labels: bug, ECMPS Prod Team

#1308 fix: column width
  src/components/AdminMaintenance/EmSubmissionData/EmSubmissionData.js
Labels: bug, ECMPS Prod Team

#1312 Bug/5753-qa-data-mats-import-populate-dropdowns
  src/components/ImportModal/ImportModalMatsContent/ImportModalMatsContent.js
Labels: ECMPS Prod Team

#1314 feature/Revamped-Styling
  src/components/EvaluateAndSubmit/ColumnMappings.js
  src/components/EvaluateAndSubmit/FilterForm/FilterForm.js
  src/components/EvaluateAndSubmit/ReviewCell/ReviewCell.js
  src/components/EvaluateAndSubmit/TableRender/TableRender.js
  src/components/MonitoringPlanTab/MonitoringPlanTab.js
  src/components/export/ExportTable/ExportTable.js
  src/styles/_react-datatable-overrides.scss
  src/utils/functions.js
Labels: Tech Team

#1316 Feature/5712-calendar-cutoff
  src/components/Modal/Modal.js
  src/components/ModalDetails/ModalDetails.js
  src/components/ModalDetails/ModalDetails.scss
Labels: ECMPS Prod Team

#1319 style/Report
  src/components/ReportGenerator/DefaultTemplate/DefaultTemplate.js
  src/components/ReportGenerator/PropertyTableTemplate/PropertyTableTemplate.js
Labels: Tech Team

#1320 Feature/5758 mp qualification add edit pop out
  src/additional-functions/retrieve-dropdown-api.js
  src/components/datatablesContainer/DataTableQualifications/DataTableQualifications.js
Labels: ECMPS Prod Team

#1318 Feature/5746 config view
  src/components/DataTableRender/DataTableRender.js
  src/components/DataTableRender/DataTableRender.scss
  src/components/datatablesContainer/DataTableConfigurations/DataTableConfigurations.js
Labels: ECMPS Prod Team

#1322 feature/New-Template
  src/components/ReportGenerator/DefaultTemplate/DefaultTemplate.js
  src/components/ReportGenerator/PropertyTableTemplate/PropertyTableTemplate.js
  src/components/ReportGenerator/Report/Report.js
Labels: Tech Team

#1323 5774-fix-data-table-styling-issues
  src/components/DataTableRender/DataTableRender.js
Labels: ECMPS Prod Team

#1326 fix/Oris
  src/components/EvaluateAndSubmit/DataTables/DataTables.js
Labels: Tech Team

#1331 Bug/5773-qa remove-unnecessary-expandable-rows
  src/components/qaDatatablesContainer/QAExpandableRowsRender/QAExpandableRowsRender.js
Labels: ECMPS Prod Team

#1333 Bug: MP Analyzer Ranges
  src/components/datatablesContainer/DataTableSystemsComponents/DataTableSystemsComponents.js
Labels: bug, ECMPS Prod Team

#1329 Feature/5250 UI top menu
  src/components/Layout/Layout.js
  src/components/LeftNavigation/LeftNavigation.js
  src/components/SubHeader/LeftNavToSubHeader.js
  src/components/SubHeader/LeftNavToSubHeader.test.js
  src/styles/_uswds-overrides.scss
  src/utils/constants/menuTopics.js
Labels: ECMPS Prod Team

#1339 🐛Bug/5789: QA Test Summary Record Error Message
  src/components/qaDatatablesContainer/QACertEventTestExmpDataTable/QACertEventTestExmpDataTable.js
  src/components/qaDatatablesContainer/QATestSummaryDataTable/QATestSummaryDataTable.js
Labels: bug, ECMPS Prod Team

#1335 Bug/5785-qa-cert-test-code-dropdown
  src/components/qaDatatablesContainer/QACertEventTestExmpDataTable/QACertEventTestExmpDataTable.js
Labels: ECMPS Prod Team

#1341 fix/Submission
  src/components/EvaluateAndSubmit/DataTables/DataTables.js
Labels: Tech Team

#1340 Bug/5807-Admin-QA/Cert-Data-Require-Resubmission-Functionality
  src/components/AdminMaintenance/QAMaintenance/QAMaintenanceData.js
  src/components/AdminMaintenance/QAMaintenance/QAMaintenanceModalPopout.js
Labels: Tech Team

#1332 sort and add code to front of description
  src/components/qaDatatablesContainer/QACertEventTestExmpDataTable/QACertEventTestExmpDataTable.js
Labels: ECMPS Prod Team

#1330 fix import file error message
  src/components/HeaderInfo/HeaderInfo.js
Labels: ECMPS Prod Team

#1345 restrict qual type code dropdown to qual types with group pct, lee, l…
  src/components/datatablesContainer/DataTableQualifications/DataTableQualifications.js
Labels: ECMPS Prod Team

#1346 Bug/5797-qa-test-missing-traverse-point-data
  src/components/qaDatatablesContainer/QAExpandableRowsRender/QAExpandableRowsRender.js
Labels: ECMPS Prod Team

#1342 Bug/5809 facility name header layout
  src/components/HeaderInfo/HeaderInfo.js
  src/components/QACertEventHeaderInfo/QACertEventHeaderInfo.js
  src/components/QACertTestSummaryHeaderInfo/QACertTestSummaryHeaderInfo.js
  src/components/export/ExportTab/ExportTab.js
  src/styles/_global-styles.scss
Labels: ECMPS Prod Team

#1347 Call Workspace Export When Logged In
  src/components/export/ExportTab/ExportTab.js
Labels: ECMPS Prod Team

#1348 clone mdm data to avoid changing redux state
  src/components/datatablesContainer/DataTableQualifications/DataTableQualifications.js
Labels: ECMPS Prod Team

#1343 Feature/5788 bug qa add
  src/components/LeftNavigation/LeftNavigation.js
  src/components/ModalDetails/ModalDetails.js
  src/components/ModalDetails/ModalDetails.scss
  src/components/SubHeader/LeftNavToSubHeader.js
Labels: ECMPS Prod Team

#1350 fix: update comp-type-code validation for analyzer-range
  src/components/datatablesContainer/DataTableSystemsComponents/DataTableSystemsComponents.js
Labels: bug

#1349 fix typo
  src/additional-functions/retrieve-dropdown-api.js
Labels: ECMPS Prod Team

#1344 Feature/5782 UI overlapping text
  src/components/ModalDetails/ModalDetails.js
Labels: ECMPS Prod Team

#1353 Bug/5776 emissions view render issue
  src/components/EmissionsViewTable/EmissionsViewTable.js
Labels: ECMPS Prod Team

#1352 Bug/5808-qa-flow-run-rows-expand-logic
  src/components/QADataTableRender/QADataTableRender.js
  src/utils/selectors/QACert/TestSummary.js
Labels: ECMPS Prod Team

#1357 Bug/5837 rename rata flow run data column
  src/additional-functions/qa-dataTable-props.js
  src/components/qaDatatablesContainer/QAExpandableRowsRender/QAExpandableRowsRender.js
  src/utils/selectors/QACert/assert.js
Labels: bug

#1356 Bug/5819-UI-spacing-on-select-config-datatable
  src/components/DataTableRender/DataTableRender.js
  src/components/DataTableRender/DataTableRender.scss
Labels: ECMPS Prod Team

#1361 fix/5825-5838-Better-Cromerr-Errors
  src/components/SubmissionModal/SubmissionModal.js
Labels: Tech Team

#1359 🐛Bug/5822: CodeQL Incomplete string escaping or encoding
  src/components/LeftNavigation/LeftNavigation.js
Labels: bug, ECMPS Prod Team

#1362 🐛Bug/5789: QA Test Summary Record Error Message
  src/components/qaDatatablesContainer/QACertEventTestExmpDataTable/QACertEventTestExmpDataTable.js
  src/components/qaDatatablesContainer/QATestSummaryDataTable/QATestSummaryDataTable.js
Labels: bug, ECMPS Prod Team

#1363 Bug/5808-expand-button-logic-rata-flow
  src/components/QADataTableRender/QADataTableRender.js
Labels: ECMPS Prod Team

#1365 Bug/5859-Submission-Checkboxes-Are-Not-Available-After-A-Submission
  src/components/EvaluateAndSubmit/EvaluateAndSubmit.js
Labels: Tech Team

#1367 fix/5868-Submission-Permission-Enforcement
  src/utils/api/easeyAuthApi.js
Labels: Tech Team

#1368 feature/5829-Allow-Crit-Submissions
  src/components/EvaluateAndSubmit/DataTables/DataTables.js
  src/components/EvaluateAndSubmit/EvaluateAndSubmit.js
Labels: Tech Team
