Repository US-EPA-CAMD/easey-ecmps-ui, pull requests merged in 2023-07, with the labels that each got.

#1159 Unit-Test/5349: ECMPS Unit Test
  craco.config.js
  src/components/App/App.test.js
  src/components/ConfirmActionModal/ConfirmActionModal.test.js
  src/components/ContactUs/ContactUs.test.js
  src/mocks/styleMock.js
Labels: Emissioners

#1160 Testing/5351 test files group 7
  src/components/DataTableRender/DataTableRender.js
  src/components/Modal/Modal.js
  src/components/datatablesContainer/DataTableAssert/DataTableAssert.test.js
  src/components/datatablesContainer/DataTableAssert/mocks.js
  src/components/datatablesContainer/DataTableConfigurations/DataTableConfigurations.test.js
  src/components/datatablesContainer/DataTableLEEQualifications/DataTableLEEQualifications.test.js
  src/components/datatablesContainer/DataTableLEEQualifications/mocks.js
  src/components/datatablesContainer/DataTableLMEQualifications/DataTableLMEQualifications.test.js
  src/components/datatablesContainer/DataTableLMEQualifications/mocks.js
  src/mocks/constants.js
  src/mocks/functions.js
Labels: Emissioners

#1161 Feature/5350 unit tests
  src/components/CountdownTimer/CountdownTImer.test.js
  src/components/CountdownTimer/CountdownTimer.js
  src/components/CustomAccordion/CustomAccordion.js
  src/components/CustomAccordion/CustomAccordion.test.js
  src/components/DataTableRender/DataTableRender.test.js
  src/components/datatablesContainer/DataTableAnalyzerRanges/DataTableAnalyzerRanges.js
  src/components/datatablesContainer/DataTableAnalyzerRanges/DataTableAnalyzerRanges.test.js
  src/mocks/constants.js
  src/mocks/functions.js
Labels: Emissioners

#1163 Feature/5456 bug qa record
  src/components/QADataTableRender/QADataTableRender.js
  src/components/qaDatatablesContainer/QAExpandableRowsRender/QAExpandableRowsRender.js
  src/components/qaDatatablesContainer/QATestSummaryDataTable/QATestSummaryDataTable.js
Labels: Emissioners

#1162 Feature/5238 qa cert maintenance table
  src/components/AdminMaintenance/AdminMaintenance.js
  src/components/AdminMaintenance/FilterFormAdmin/FilterFormAdmin.js
  src/components/AdminMaintenance/QAMaintenance/QAMaintenanceData.js
  src/components/AdminMaintenance/QAMaintenance/QAMaintenanceDataColumns.js
  src/utils/api/adminManagementApi.js
Labels: Emissioners

#1165 add qa maintenance modal popout
  src/components/AdminMaintenance/QAMaintenance/QAMaintenanceData.js
  src/components/AdminMaintenance/QAMaintenance/QAMaintenanceModalPopout.js
Labels: Emissioners

#1166 Bug/5311-evaluate-508-issue
  src/components/EvaluateAndSubmit/DataTables/DataTables.js
  src/components/EvaluateAndSubmit/ReviewCell/ReviewCell.js
  src/components/EvaluateAndSubmit/TableRender/TableRender.js
Labels: Emissioners

#1167 Bug/5310-export-page-508-issue
  src/additional-functions/ensure-508.js
  src/components/export/ExportTab/ExportTablesContainer.js
Labels: Emissioners

#1171 Feature/5407 require resubmission api call
  src/components/AdminMaintenance/AdminMaintenance.js
  src/components/AdminMaintenance/EmSubmissionData/EmSubmissionData.js
  src/components/AdminMaintenance/QAMaintenance/QAMaintenanceData.js
  src/components/AdminMaintenance/QAMaintenance/QAMaintenanceModalPopout.js
  src/utils/api/adminManagementApi.js
Labels: Emissioners

#1174 Bug/5312-error-suppression-page-508-issue
  src/additional-functions/ensure-508.js
  src/components/ErrorSuppression/ErrorSuppressionDataContainer/ErrorSuppressionDataContainer.js
  src/components/ErrorSuppression/ErrorSuppressionFilters/ErrorSuppressionFilters.js
Labels: Emissioners

#1176 fix identifiers for cert event and test extension exemption
  src/components/AdminMaintenance/QAMaintenance/QAMaintenanceModalPopout.js
Labels: Emissioners

#1173 feature/5303-focus-issue-mp
  src/additional-functions/manage-focus.js
  src/components/datatablesContainer/DataTableAssert/DataTableAssert.js
Labels: Emissioners

#1172 feature/5306-508-mp-error-msg
  src/additional-functions/create-modal-input-controls.test.js
  src/additional-functions/dataTable-props.js
  src/additional-functions/extract-user-input.test.js
  src/components/ModalDetails/ModalDetails.test.js
  src/components/datatablesContainer/DataTableAnalyzerRanges/DataTableAnalyzerRanges.js
  src/components/datatablesContainer/DataTableAssert/mocks.js
  src/components/datatablesContainer/DataTableMats/DataTableMats.js
  src/components/datatablesContainer/DataTableMethod/DataTableMethod.js
  src/components/datatablesContainer/DataTableQualifications/DataTableQualifications.js
  src/components/datatablesContainer/DataTableRectangularDucts/DataTableRectangularDucts.js
  src/components/datatablesContainer/DataTableSystems/DataTableSystems.js
  src/components/datatablesContainer/DataTableSystemsComponents/DataTableSystemsComponents.js
Labels: Emissioners

#1177 Feature/5302-api-error-alert-508-issue
  src/components/Layout/Layout.js
Labels: Emissioners

#1179 Test/5352
  src/components/DataTableRender/DataTableRender.js
  src/components/datatablesContainer/DataTableMats/DataTableMats.test.js
  src/components/datatablesContainer/DataTableMats/mocks.js
  src/components/datatablesContainer/DataTableMethod/DataTableMethod.test.js
  src/components/datatablesContainer/DataTableMethod/mocks.js
  src/components/datatablesContainer/DataTablePCTQualifications/DataTablePCTQualifications.test.js
  src/components/datatablesContainer/DataTablePCTQualifications/mocks.js
  src/components/datatablesContainer/DataTableQualifications/DataTableQualifications.test.js
  src/components/datatablesContainer/DataTableQualifications/mocks.js
Labels: Emissioners

#1181 add unit tests
  package.json
  src/components/datatablesContainer/DataTableRectangularDucts/DataTableRectangularDucts.test.js
  src/components/datatablesContainer/DataTableSystems/DataTableSystems.test.js
  src/components/datatablesContainer/DataTableSystemsComponents/DataTableSystemsComponents.test.js
  src/components/datatablesContainer/SelectFacilitiesDataTable/SelectFacilitiesDataTable.test.js
  yarn.lock
Labels: Testing

#1182 Bug/5310-export-page-508-prod-build-issue
  src/components/datatablesContainer/DataTableAssert/DataTableAssert.js
  src/components/export/ExportTab/ExportTablesContainer.js
Labels: Emissioners

#1183 Feature/5354 unit test 10
  src/components/DetailsSelectBox/DetailsSelectBox.test.js
  src/components/DropdownSelection/DropdownSelection.test.js
  src/components/DynamicTabs/DynamicTabs.test.js
  src/components/DynamicTabs/mocks.js
  src/components/EmissionsTab/EmissionsTab.test.js
  src/components/EmissionsTab/mocks.js
  src/components/Tabs/Tabs.js
Labels: Emissioners

#1186 🐛 Bug/5517: EM Submission Access Filters
  src/components/AdminMaintenance/FilterFormAdmin/FilterFormAdmin.js
  src/components/AdminMaintenance/FilterFormAdmin/FilterFormAdmin.test.js
Labels: Emissioners

#1187 disable buttons conditionally
  src/components/AdminMaintenance/EmSubmissionData/EmSubmissionData.js
Labels: Emissioners

#1188 Bug/5484-test-qual-air-emissions-protocol-gas-crud-not-working
  src/components/QADataTableRender/QADataTableRender.js
  src/components/qaDatatablesContainer/QAExpandableRowsRender/QAExpandableRowsRender.js
  src/utils/selectors/QACert/assert.js
  src/utils/selectors/QACert/assert.test.js
Labels: Emissioners

#1190 Unit-Test/5357: ECMPS Test Files Group 13
  craco.config.js
  src/components/EvaluateAndSubmit/DataTables/DataTables.test.js
Labels: Emissioners

#1189 Bug/5485 mp systems
  src/components/datatablesContainer/DataTableSystems/DataTableSystems.js
  src/components/datatablesContainer/DataTableSystems/DataTableSystems.test.js
Labels: Emissioners

#1191 Feature/5491 view cpms qual
  src/additional-functions/data-table-section-and-store-names.js
  src/additional-functions/data-table-section-and-store-names.test.js
  src/components/datatablesContainer/DataTableCPMSQualifications/DataTableCPMSQualifications.js
  src/components/datatablesContainer/DataTableCPMSQualifications/DataTableCPMSQualifications.test.js
  src/components/datatablesContainer/DataTableCPMSQualifications/mocks.js
  src/components/datatablesContainer/DataTablePCTQualifications/DataTablePCTQualifications.js
  src/components/datatablesContainer/DataTableQualifications/DataTableQualifications.js
  src/store/reducers/initialState.js
  src/utils/api/monitoringPlansApi.js
  src/utils/selectors/monitoringPlanCPMSQualifications.js
Labels: Emissioners Emissions

#1192 Feature/5516 display resubmission reason
  src/components/AdminMaintenance/FilterFormAdmin/FilterFormAdmin.js
  src/components/AdminMaintenance/QAMaintenance/QAMaintenanceData.js
  src/components/AdminMaintenance/QAMaintenance/QAMaintenanceDataColumns.js
  src/components/AdminMaintenance/QAMaintenance/QAMaintenanceModalPopout.js
Labels: Emissioners

#1193 Unit-Tests/5358: ECMPS Test Files Group 14
  src/components/EvaluateAndSubmit/FilterForm/FilterForm.test.js
  src/components/EvaluateAndSubmit/ReviewCell/ReviewCell.test.js
  src/components/EvaluateAndSubmit/utils/functions.test.js
Labels: Emissioners

#1194 test/5374-ecmps-test-file-group-29
  src/components/WideHeader/WideHeader.js
  src/components/WideHeader/WideHeader.scss
  src/components/WideHeader/WideHeader.test.js
  src/components/WideHeaderMenu/Menu.js
  src/components/WideHeaderMenu/Menu.scss
  src/components/WideHeaderMenu/Menu.test.js
  src/components/WideHeaderMenu/menuTopics.js
  src/components/WideHeaderMenu/svgs.js
  src/mocks/constants.js
  src/mocks/render.js
  src/store/actions/facilities.test.js
  src/store/reducers/apiStatusReducer.test.js
Labels: Emissioners

#1197 Fix security vulnerability
  package.json
  yarn.lock
Labels: Tech Team

#1198 add unit tests
  src/components/FAQ/FAQ.js
  src/components/FAQ/FAQ.test.js
  src/components/Footer/Footer.test.js
  src/components/GenericTable/GenericTable.test.js
  src/components/HeaderInfo/EmissionsImportTypeModalContent.test.js
Labels: Testing

#1199 Unit-Tests/5362: ECMPS Test Files Group 18
  package.json
  src/components/ImportModal/ImportModal.test.js
  src/components/ImportModal/import-functions.test.js
  src/components/InactivityTracker/InactivityTracker.test.js
  src/components/Layout/Layout.test.js
Labels: Emissioners

#1203 Unit-Tests/5373: ECMPS Test Files Group 28
  package.json
  src/components/SubHeader/LeftNavToSubHeader.test.js
  src/components/SubHeader/SubHeader.test.js
  src/components/SubmissionModal/SubmissionModal.test.js
  src/components/Tabs/Tabs.test.js
Labels: Emissioners

#1200 Test/5363-unit-test-update-group-19
  src/components/Footer/Footer.js
  src/components/Footer/Footer.scss
  src/components/Footer/Footer.test.js
  src/components/Footer/epaSeal.svg
  src/components/LeftNavigation/LeftNavigation.test.js
  src/components/LoadingModal/LoadingModal.test.js
  src/components/Login/Login.js
  src/components/Login/Login.test.js
  src/components/Menu/Menu.js
  src/components/Menu/Menu.scss
  src/components/Menu/Menu.test.js
  src/mocks/functions.js
Labels: Emissioners
