Repository US-EPA-CAMD/easey-ecmps-ui, pull requests merged in 2023-09, with the labels that each got.

#1244 Bug/5586 emissions import historical
  src/components/HeaderInfo/ImportHistoricalDataModal.js
  src/utils/api/emissionsApi.js
Labels: Emissioners

#1245 change to handleImportError to prevent error from displaying in backg…
  src/utils/api/emissionsApi.js
Labels: Emissioners

#1247 feature/Advanced-Filtering
  src/components/ImportModal/ImportModalMatsContent/ImportModalMatsContent.js
  src/components/QACertTestSummaryHeaderInfo/QACertTestSummaryHeaderInfo.js
  src/utils/api/camdServices.js
Labels: Tech Team

#1246 Bug/5254-emissions-reporting-period-dropdown
  src/components/HeaderInfo/HeaderInfo.js
Labels: Emissioners

#1248 fix/Mats-Submission
  src/components/EvaluateAndSubmit/ColumnMappings.js
  src/components/EvaluateAndSubmit/EvaluateAndSubmit.js
Labels: Tech Team

#1250 Feature/5610-mp-systems-add-analytical-principle-code
  src/additional-functions/retrieve-dropdown-api.js
  src/components/datatablesContainer/DataTableSystems/DataTableSystems.js
  src/components/datatablesContainer/DataTableSystemsComponents/DataTableSystemsComponents.js
  src/utils/api/dataManagementApi.js
Labels: Emissioners

#1251 Feature/5609 mp schema updates
  src/additional-functions/dataTable-props.js
  src/additional-functions/qa-dataTable-props.js
  src/additional-functions/retrieve-dropdown-api.js
  src/additional-functions/retrieve-dropdown-api.test.js
  src/components/ErrorSuppression/ErrorSuppressionFilters/ErrorSuppressionFilters.js
  src/components/ImportModal/ImportModal.test.js
  src/components/datatablesContainer/DataTableSystems/DataTableSystems.js
  src/components/datatablesContainer/DataTableSystems/DataTableSystems.test.js
  src/components/datatablesContainer/DataTableSystemsComponents/DataTableSystemsComponents.js
  src/components/datatablesContainer/DataTableSystemsComponents/DataTableSystemsComponents.test.js
  src/components/qaDatatablesContainer/QAExpandableRowsRender/QAExpandableRowsRender.test.js
  src/mocks/constants.js
  src/utils/selectors/QACert/TestSummary.js
  src/utils/selectors/monitoringPlanDefaults.test.js
  src/utils/selectors/monitoringPlanSystems.test.js
Labels: Emissioners

#1256 feature/Report-Download
  src/components/ReportGenerator/DefaultTemplate/DefaultTemplate.js
  src/components/ReportGenerator/Report/Report.js
  src/components/ReportGenerator/ReportGenerator.js
  src/styles/_react-datatable-overrides.scss
  src/utils/api/camdServices.js
  src/utils/functions.js
Labels: Tech Team

#1255 feature/5648-error-suppression-bug-fix-and-datatable-record-id
  src/components/ErrorSuppression/ErrorSuppressionDataContainer/ErrorSuppressionDataContainer.js
  src/components/ErrorSuppression/ErrorSuppressionFilters/ErrorSuppressionFilters.js
Labels: Emissioners

#1257 🐛 Bug/5645: Unable to Open Facilities
  src/components/DynamicTabs/DynamicTabs.js
  src/components/EmissionsTab/EmissionsTab.js
  src/components/EmissionsTabRender/EmissionsTabRender.js
  src/components/HeaderInfo/HeaderInfo.js
  src/components/MonitoringPlanTab/MonitoringPlanTab.js
  src/components/QACertEventTab/QACertEventTab.js
  src/components/QACertTestSummaryTab/QACertTestSummaryTab.js
  src/components/export/ExportTab/ExportTab.js
  src/components/export/ExportTab/ExportTablesContainer.js
Labels: Emissioners, bug

#1258 🐛Bug-508/5640: Error Suppression Check-Box & View-button Labels
  src/components/ErrorSuppression/ErrorSuppressionDataContainer/ErrorSuppressionDataContainer.js
Labels: Emissioners, bug

#1262 Feature/5631-Export-Refactor
  src/components/ReportingPeriodSelector/ReportingPeriodSelector.js
  src/components/export/ExportTab/ExportTab.js
  src/components/export/ExportTable/ExportTable.js
  src/components/export/SelectableDataTable/SelectableDataTable.js
  src/components/export/SelectableDataTable/SelectableDataTable.scss
  src/styles/_react-datatable-overrides.scss
  src/utils/api/apiUtils.js
  src/utils/api/monitoringPlansApi.js
  src/utils/api/qaCertificationsAPI.js
Labels: Tech Team

#1263 fix/Checkbox
  src/components/export/SelectableDataTable/SelectableDataTable.scss
Labels: Tech Team

#1259 Feature/5649 error messaging admin module
  src/components/ErrorSuppression/AddErrorSuppressionModal/AddErrorSuppressionModal.js
  src/components/ErrorSuppression/ErrorSuppressionDataContainer/ErrorSuppressionDataContainer.js
  src/components/HeaderInfo/HeaderInfo.js
  src/components/Modal/Modal.js
  src/components/datatablesContainer/DataTableSystems/DataTableSystems.js
  src/components/datatablesContainer/DataTableSystemsComponents/DataTableSystemsComponents.js
  src/components/qaDatatablesContainer/QACertEventTestExmpDataTable/__snapshots__/QACertEventTestExmpDataTable.test.js.snap
  src/utils/api/errorSuppressionApi.js
Labels: Emissioners Emissions

#1261 Bug/5650 monitoring plan scroll issue
  src/components/DataTableRender/DataTableRender.js
  src/components/datatablesContainer/DataTableCPMSQualifications/DataTableCPMSQualifications.js
  src/components/datatablesContainer/DataTableLEEQualifications/DataTableLEEQualifications.js
  src/components/datatablesContainer/DataTableLMEQualifications/DataTableLMEQualifications.js
  src/components/datatablesContainer/DataTablePCTQualifications/DataTablePCTQualifications.js
  src/components/datatablesContainer/DataTableSystemsComponents/DataTableSystemsComponents.js
Labels: Emissioners

#1266 fix/Global-Export
  src/components/export/ExportTab/ExportTab.js
  src/utils/api/emissionsApi.js
  src/utils/api/monitoringPlansApi.js
  src/utils/api/qaCertificationsAPI.js
Labels: Tech Team

#1265 Feature/5665 export page
  src/utils/constants/menuTopics.js
Labels: Emissioners

#1267 Feature/bug 5691 sys comp
  src/components/datatablesContainer/DataTableSystems/DataTableSystems.js
Labels: Emissioners

#1269 🐛 Bug-508/5637: Error Suppression Table Header Cells
  src/additional-functions/ensure-508.js
  src/components/AdminMaintenance/FilterFormAdmin/FilterFormAdmin.js
  src/components/ErrorSuppression/ErrorSuppressionDataContainer/ErrorSuppressionDataContainer.js
Labels: bug, ECMPS Prod Team

#1270 Feature/5665 export page
  src/utils/constants/menuTopics.js
Labels: Emissioners

#1264 Feature/508 focus error suppression
  src/components/ErrorSuppression/ErrorSuppressionDataContainer/ErrorSuppressionDataContainer.js
Labels: Emissioners

#1273 Bug/data save export report page
  src/components/export/ExportTab/ExportTab.js
  src/components/export/ExportTable/ExportTable.js
  src/components/export/SelectableDataTable/SelectableDataTable.js
Labels: Emissioners

#1271 Feature/5695 importing
  src/components/ImportModal/import-functions.js
Labels: Emissioners, Emissioners Emissions

#1272 Feature/5689-runtime-error-handling
  package.json
  src/components/ErrorFallbackModal/ErrorFallbackModal.js
  src/components/ErrorFallbackModal/ErrorFallbackModal.scss
  src/components/ErrorFallbackModal/ErrorFallbackModal.test.js
  src/index.js
  yarn.lock
Labels: ECMPS Prod Team

#1276 Feature/5643 508 error suppression
  src/additional-functions/ensure-508.js
  src/components/ErrorSuppression/ErrorSuppressionDataContainer/ErrorSuppressionDataContainer.js
Labels: Emissioners

#1279 fix/Export-Auth
  src/components/export/ExportTab/ExportTab.js
  src/components/export/ExportTable/ExportTable.js
  src/utils/api/easeyAuthApi.js
Labels: Tech Team
