Repository US-EPA-CAMD/easey-ecmps-ui, pull requests merged in 2023-11, with the labels that each got.

#1369 Feature/5854 eval status
  src/components/HeaderInfo/HeaderInfo.js
  src/components/ModalDetails/ModalDetails.js
  src/components/datatablesContainer/DataTableQualifications/DataTableQualifications.js
  src/components/datatablesContainer/DataTableSystems/DataTableSystems.js
  src/components/export/ExportTab/ExportTab.js
Labels: ECMPS Prod Team

#1371 Update EmissionsViewTable.js
  src/components/EmissionsViewTable/EmissionsViewTable.js
Labels: ECMPS Prod Team

#1373 Bug/5755-mp-formulas-dropdown-filtering
  src/components/datatablesContainer/DataTableAssert/DataTableAssert.js
Labels: ECMPS Prod Team

#1375 Feature/5889-update-mp-component-type-dropdown-label
  src/components/datatablesContainer/DataTableSystemsComponents/DataTableSystemsComponents.js
Labels: ECMPS Prod Team

#1377 feature/5886-Eval-Submit-Review
  src/components/EvaluateAndSubmit/CategoryTable/CategoryTable.js
  src/components/EvaluateAndSubmit/CategoryTable/CategoryTable.scss
  src/components/EvaluateAndSubmit/DataTables/DataTables.js
  src/components/EvaluateAndSubmit/DataTables/DataTables.scss
  src/components/EvaluateAndSubmit/DataTables/DataTables.test.js
  src/components/EvaluateAndSubmit/EvaluateAndSubmit.js
  src/components/EvaluateAndSubmit/EvaluateRefresh.js
  src/components/EvaluateAndSubmit/FilterForm/FilterForm.js
  src/components/EvaluateAndSubmit/ReviewCell/ReviewCell.js
  src/components/EvaluateAndSubmit/ReviewCell/ReviewCell.test.js
  src/components/EvaluateAndSubmit/SelectableDataTable/SelectableDataTable.js
  src/components/EvaluateAndSubmit/SelectableDataTable/SelectableDataTable.scss
  src/components/EvaluateAndSubmit/TableRender/TableRender.js
  src/components/EvaluateAndSubmit/TableRender/TableRender.scss
  src/components/EvaluateAndSubmit/TableRender/TableRender.test.js
  src/components/EvaluateAndSubmit/utils/functions.js
  src/components/EvaluateAndSubmit/utils/functions.test.js
  src/components/ReportGenerator/Report/Report.js
  src/components/SubmissionAlertModal/SubmissionAlertModal.js
  src/components/SubmissionAlertModal/SubmissionAlertModal.test.js
  src/components/export/SelectableDataTable/SelectableDataTable.js
  src/utils/api/monitoringPlansApi.js
  src/utils/functions.js
Labels: Tech Team

#1376 bug/5808-undo-expand-logic-for-qa-flow-run
  src/components/QADataTableRender/QADataTableRender.js
  src/utils/selectors/QACert/TestSummary.js
Labels: ECMPS Prod Team

#1374 Feature/5854 eval status
  src/components/HeaderInfo/HeaderInfo.js
  src/components/datatablesContainer/DataTableSystems/DataTableSystems.js
Labels: ECMPS Prod Team

#1378 set default values to 0 if null/undefined
  src/additional-functions/extract-user-input.js
Labels: ECMPS Prod Team

#1380 🐛Bug/5900: UI Homepage Top Menu
  src/components/Layout/Layout.js
  src/components/MenuSearch/MenuSearch.js
  src/components/MenuSearch/MenuSearch.scss
  src/components/MenuSearch/MenuSearch.test.js
Labels: bug, ECMPS Prod Team

#1383 Bug/5881 mp default section
  src/additional-functions/create-modal-input-controls.js
  src/additional-functions/dataTable-props.js
  src/components/datatablesContainer/DataTableAssert/DataTableAssert.js
Labels: ECMPS Prod Team

#1379 Feature/bug modal error
  src/components/datatablesContainer/DataTableQualifications/DataTableQualifications.js
  src/components/datatablesContainer/DataTableSystems/DataTableSystems.js
Labels: ECMPS Prod Team

#1384 fix/Added-Crit-Sub-Code
  src/components/EvaluateAndSubmit/utils/functions.js
Labels: Tech Team

#1386 bug/5908-add-edit-bug-in-fuel-flow-to-load-baseline
  src/additional-functions/qa-dataTable-props.js
Labels: ECMPS Prod Team
